// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuynpHk9D4hvoCwajiXrSLRL0lBVjfJ6E',
    appId: '1:379939966281:web:dc4c6d48912e2c63d49e98',
    messagingSenderId: '379939966281',
    projectId: 'web-quiz-app-ed588',
    authDomain: 'web-quiz-app-ed588.firebaseapp.com',
    storageBucket: 'web-quiz-app-ed588.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkqQpw0pC5pj6Umi-UGO8F3twUmppv-5w',
    appId: '1:379939966281:android:48ea9ec90e63621ed49e98',
    messagingSenderId: '379939966281',
    projectId: 'web-quiz-app-ed588',
    storageBucket: 'web-quiz-app-ed588.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhFIekXHpEU7utyxqomOc-GoSDmW1A4Cw',
    appId: '1:379939966281:ios:0d6733d1a3c645add49e98',
    messagingSenderId: '379939966281',
    projectId: 'web-quiz-app-ed588',
    storageBucket: 'web-quiz-app-ed588.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );
}
